import Head from "next/head";
import Image from "next/image";
import About from "../../components/About";
import Event from "../../components/Event";
import Hero from "../../components/Hero";
import Sponsors from "../../components/Sponsors";

const index = () => {
  return (
    <div>
      <Head>
        <title>Montreal Canada Day Parade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title="Montreal Canada Day Parade"
        subtitle="Donate for the perfect event"
        image="/hero.png"
        btn={true}
      />
      <Event />
      <About />
      <Sponsors />
    </div>
  );
};

export default index;
